name: multigit # you probably want to 'snapcraft register <name>'
base: core22 
version: '1.6.1-rc1'
summary: Graphical tool for working with projects composed of multiple git repositories
description: |
        Multigit is a graphical tool for working with projects composed of multiple git repositories.

        If you think that *submodules*, *subtree* or *Google repo* are not for you, you are probably at the
        right place.

        Typically, it lets you:
        * fetch or pull on many repositories at the same time
        * identify visually which repositories are modified or need an update (push or pull)
        * create a new branch in a subset of repositories
        * switch to a branch existing only in some repositories (but you don't remember which one)
        * perform a commit on multiple repositories at the same time, and push it
        * launch your preferred git frontend on an interesting repository
        * export your repositories state to a file, for reproducing it on a colleagues computer
        * and more...


grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

plugs:
  gitconfig:
    interface: personal-files
    read:
      - $HOME/.gitconfig         # the old location
      - $HOME/.config/git/config # the new location (people could change it via XDG_CONFIG_HOME and that isn't supported by snapd yet)
      - $HOME/.git-credentials
  etc-gitconfig:
    interface: system-files
    read:
      - /etc/gitconfig


parts:
  multigit:
    plugin: python
    source: .
    stage-packages: [git]
    python-packages: [ pip, setuptools, wheel ]


apps:
  multigit:
    command: bin/multigit
    environment:
      GIT_TEMPLATE_DIR: $SNAP/usr/share/git-core/templates
      GIT_CONFIG_NOSYSTEM: "true"
      GIT_EXEC_PATH: $SNAP/usr/lib/git-core
      GIT_TEXTDOMAINDIR: $SNAP/usr/share/locale
    extensions:
      - kde-neon # needed for pulling Qt5
    plugs:
      - home # to have access to the filesystem
      - removable-media # so it can access things in /media, etc
      - gitconfig       # so it can access ~/.gitconfig :-)
      - etc-gitconfig   # so it can access /etc/gitconfig
      - ssh-keys
      - network # for git cloning, pulling, pushing



