
name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-windows-python:

    runs-on: windows-latest, ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          # oldest supported version of python
          - python-version: "3.7"

          # limit python version to 3.10 due to Pyside2
          # not supported at the moment, fix that later
          # - python-version: "3.10"

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install -r requirements-dev.txt
        pip list

    - name: run tests
      run: |
        pytest

    - name: run type checking
      run: |
        mypy .
