
name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-windows-python:

    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # oldest version of pyhon / mypy which works
          - python-version: "3.8"

          # latest version of everything
          - python-version: "3.11"

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install -r requirements-dev.txt
        pip list

    - name: run tests
      run: |
        mypy .
